version: '3.1'

services:

  proxy:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443